version: '3.9'

services:
  be:
    image: be
    ports:
      - "8080:8080"

  fe:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - API_BASE=be:8080
    depends_on:
      - be